api/configuration/v1beta1/kongconsumergroup_types.go
Add GetTypeName() for KongConsumerGroup
=> chore: add GetTypeName() for KongConsumerGroup

CODEOWNERS
Makes @Kong/k8s-maintainers code owners on this repo.
=> chore: add Kong/k8s-maintainers as CODEOWNERS

api/configuration/v1alpha1/kongservice_types.go, api/configuration/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/configuration.konghq.com_kongservices.yaml, docs/api-reference.md
This removes the KonnectAPIAuthConfiguration reference from KongService in favor of relying on referenced control plane API auth config.
Fixes #
=> refactor(konnect): KongService remove KonnectAPIAuthConfiguration ref

api/configuration/v1alpha1/kongroute_types.go, api/konnect/v1alpha1/konnect_apiauthconfiguration_types.go, api/konnect/v1alpha1/konnect_configuration.go, api/konnect/v1alpha1/konnect_controlplane_types.go, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongroutes.yaml, config/crd/bases/konnect.konghq.com_konnectapiauthconfigurations.yaml, config/crd/bases/konnect.konghq.com_konnectcontrolplanes.yaml, go.mod, go.sum, test/crdsvalidation/kongpluginbindings/kongpluginbindings_test.go, test/crdsvalidation/konnectcontrolplane/konnectcontrolplane_test.go, test/crdsvalidation/konnectcontrolplane/testcases/common.go, test/crdsvalidation/konnectcontrolplane/testcases/update-not-allowed-for-status.go
This PR makes it possible to fix a broken authRef instead of requiring users to delete the object and recreate it with a fixed authRef.
This change makes the authRef mutable when 
- entity does not have a `Programmed` condition with status set to `True`
- entity does not have a `APIAuthValid` condition with status set to `True`
Fixes #
=> feat: make konnect entities spec.konnect.authRef immutable only when entity is already programmed

test/crdsvalidation/kongpluginbindings/kongpluginbindings_test.go, test/crdsvalidation/konnectcontrolplane/konnectcontrolplane_test.go
We need to always run the cleanup. In case an error in the creation was occurred, `client.IgnoreNotFound` does not return any error in the creation.
Fixes #
=> chore: always execute the cleanup

api/configuration/v1alpha1/kongpluginbinding_types.go, config/crd/bases/configuration.konghq.com_kongpluginbindings.yaml
=> chore: `KongPluginBinding` printColumn fixed

api/configuration/v1/kongconsumer_types.go, api/configuration/v1alpha1/kongpluginbinding_types.go, api/configuration/v1alpha1/kongroute_types.go, api/configuration/v1alpha1/kongservice_types.go, api/configuration/v1alpha1/service_ref.go, api/configuration/v1beta1/kongconsumergroup_types.go, api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongpluginbindings.yaml, config/crd/bases/configuration.konghq.com_kongroutes.yaml, config/crd/bases/configuration.konghq.com_kongservices.yaml, config/crd/bases/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, docs/api-reference.md, test/crdsvalidation/kongconsumer/testcases/cpref-update-not-allowed-for-status.go, test/crdsvalidation/kongconsumergroup/testcases/cpref-update-not-allowed-for-status.go, test/crdsvalidation/kongpluginbindings/testcases/cpref-update-not-allowed-for-status.go, test/crdsvalidation/kongroute/kongroute_test.go, test/crdsvalidation/kongroute/testcases/common.go, test/crdsvalidation/kongroute/testcases/protocols.go, test/crdsvalidation/kongroute/testcases/serviceref.go, test/crdsvalidation/kongservice/testcases/controlplaneref.go, test/crdsvalidation/konnectgatewaycontrolplane/testcases/update-not-allowed-for-status.go
Adds missing `KongRoute` CEL rules and fixes the existing one for `protocols` that was failing when no `protocols` is provided (which should be correct).
=> fix: make KongRoute CEL validations work as expected

README.md, api/configuration/v1alpha1/kongupstream_types.go, config/crd/bases/configuration.konghq.com_kongupstreams.yaml, config/crd/kustomization.yaml, test/crdsvalidation/kongupstream/kongupstream_test.go, test/crdsvalidation/kongupstream/testcases/common.go, test/crdsvalidation/kongupstream/testcases/controlplaneref.go, test/crdsvalidation/kongupstream/testcases/required_fields.go
Add CRD validation tests for KongUpstream and add validation rules to KongUpstream spec.
Required for https://github.com/Kong/gateway-operator/issues/575
=> feat: add CRD validation tests for KongUpstream and fix struct tags

.github/dependabot.yml
Group k8s libs bumps in dependabot config as per : https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
=> chore: group dependabot k8s libs bumps

api/configuration/v1alpha1/kong_target_types.go, config/crd/bases/configuration.konghq.com_kongtargets.yaml, config/crd/kustomization.yaml, test/crdsvalidation/kongroute/testcases/common.go, test/crdsvalidation/kongtarget/kongtarget_test.go, test/crdsvalidation/kongtarget/testcases/common.go, test/crdsvalidation/kongtarget/testcases/controlplaneref.go, test/crdsvalidation/kongtarget/testcases/kongtargetapispec.go, test/crdsvalidation/kongtarget/testcases/upstreamref.go
Add CRD validation tests and some minor fixes in `KongTarget` CRD. Also add `KongTarget` and `KongUpstream` to kustomize manifests.
required for https://github.com/Kong/gateway-operator/issues/576
Also fixed some copy-pasta errors in CRD validation tests
=> test(crd): Fix status definition of KongTarget and add CRD validations

api/configuration/v1alpha1/kong_vault_types.go, config/crd/bases/configuration.konghq.com_kongvaults.yaml, test/crdsvalidation/kongvault/kongvault_test.go, test/crdsvalidation/kongvault/testcases/common.go, test/crdsvalidation/kongvault/testcases/controlplaneref.go, test/crdsvalidation/kongvault/testcases/vaultspec.go, test/unit/konvault_test.go
Add Konnect specific validations (`spec.controlPlaneRef`) and CRD validation tests for `KongVault`.
Related to [KGO#577](https://github.com/Kong/gateway-operator/issues/577)
=> feat(crd): add konnect specific validations and crd validation tests for KongVault

.github/workflows/tests.yaml, .golangci.yaml, .tools_versions.yaml, Makefile, pkg/metadata/tags.go, pkg/metadata/tags_test.go, test/crdsvalidation/kongconsumer/kongconsumer_test.go, test/crdsvalidation/kongconsumergroup/kongconsumergroup_test.go, test/crdsvalidation/kongpluginbindings/kongpluginbindings_test.go, test/crdsvalidation/kongroute/kongroute_test.go, test/crdsvalidation/kongroute/testcases/protocols.go, test/crdsvalidation/kongroute/testcases/serviceref.go, test/crdsvalidation/kongservice/kongservice_test.go, test/crdsvalidation/kongservice/testcases/controlplaneref.go, test/crdsvalidation/kongtarget/testcases/kongtargetapispec.go, test/crdsvalidation/kongtarget/testcases/upstreamref.go, test/crdsvalidation/kongupstream/kongupstream_test.go, test/crdsvalidation/kongupstream/testcases/controlplaneref.go, test/crdsvalidation/kongupstream/testcases/required_fields.go, test/crdsvalidation/kongvault/testcases/vaultspec.go, test/crdsvalidation/konnectgatewaycontrolplane/konnectgatewaycontrolplane_test.go, test/crdsvalidation/konnectgatewaycontrolplane/testcases/update-not-allowed-for-status.go
Add linter to enforce consistent code style.
=> ci: add golangci-lint

api/configuration/v1/kongconsumer_types.go, api/configuration/v1alpha1/kong_ca_certificate.go, api/configuration/v1alpha1/kongservice_types.go, api/configuration/v1alpha1/kongupstream_types.go, api/configuration/v1alpha1/konnect_controlplaneref_types.go, api/configuration/v1beta1/kongconsumergroup_types.go, config/crd/bases/configuration.konghq.com_kongcacertificates.yaml, config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongpluginbindings.yaml, config/crd/bases/configuration.konghq.com_kongservices.yaml, config/crd/bases/configuration.konghq.com_kongupstreams.yaml, config/crd/bases/configuration.konghq.com_kongvaults.yaml, docs/api-reference.md, test/crdsvalidation/kongconsumer/testcases/common.go, test/crdsvalidation/kongconsumer/testcases/controlplaneref.go, test/crdsvalidation/kongconsumergroup/testcases/common.go, test/crdsvalidation/kongconsumergroup/testcases/controlplaneref.go, test/crdsvalidation/kongservice/testcases/controlplaneref.go, test/crdsvalidation/kongupstream/testcases/controlplaneref.go
Add `namespace` in `konnectNamespacedRef` because some of Kong entities like `KongVault` and `KongClusterPlugin` are cluster scoped and they require the namespace for referring to a Konnect gateway controlplane.
#36
=> feat(konnect): add namespace in KonnectNamespacedRef

api/configuration/v1alpha1/service_ref.go, config/crd/bases/configuration.konghq.com_kongroutes.yaml, docs/api-reference.md
This PR disallows cross namespace references from `KongRoute` to `KongService`.
#106 will track the implementation of those.
Fixes #
=> feat: disallow cross namespace services refs

api/configuration/v1alpha1/zz_generated_konnect_funcs.go, scripts/konnect-funcs/templates.go, test/unit/konnect_funcs_test.go
Add generation of credential related funcs: `SetKonnectConsumerIDInStatus()` and `GetConsumerRefName()`
=> feat(generate): add generation of credential related funcs: `SetKonnectConsumerIDInStatus()` and `GetConsumerRefName()`

api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, api/konnect/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, docs/konnect-api-reference.md, test/crdsvalidation/konnectgatewaycontrolplane/testcases/common.go, test/crdsvalidation/konnectgatewaycontrolplane/testcases/members-only-allowed-on-groups.go
Add `members` field for `KonnectGatewayControlPlane` CRD to allow setting group members.
Required for https://github.com/Kong/gateway-operator/issues/449
=> feat(konnect): add KonnectControlPlane group members field

README.md, api/configuration/v1/conditions.go, api/configuration/v1/configsource.go, api/configuration/v1/kongclusterplugin_types.go, api/configuration/v1/kongconsumer_types.go, api/configuration/v1/kongingress_types.go, api/configuration/v1/kongplugin_types.go, api/configuration/v1/kongprotocol_types.go, api/configuration/v1alpha1/ingress_class_param_types.go, api/configuration/v1alpha1/kong_license_types.go, api/configuration/v1alpha1/kong_vault_types.go, api/configuration/v1beta1/ingress_rules.go, api/configuration/v1beta1/kongconsumergroup_types.go, api/configuration/v1beta1/kongupstreampolicy_types.go, api/configuration/v1beta1/tcpingress_types.go, api/configuration/v1beta1/udpingress_types.go
Annotates KIC-supported `configuration` types with the new markers that are going to be used in KIC's `crd-ref-docs` templates.
Part of https://github.com/Kong/kubernetes-configuration/issues/105.
=> chore: add KIC API reference markers

api/configuration/v1/kongconsumer_types.go, api/configuration/v1beta1/kongconsumergroup_types.go, config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, test/crdsvalidation/kongconsumer/testcases/controlplaneref.go, test/crdsvalidation/kongconsumergroup/testcases/controlplaneref.go
Fixes validations to check namespaces in `controlPlaneRef` to allow empty `controlPlaneRef` and add related tests.
Fixes #
=> fix: do not require controlPlaneRef in validation

api/configuration/v1alpha1/konnect_controlplaneref_types.go, config/crd/bases/configuration.konghq.com_kongcacertificates.yaml, config/crd/bases/configuration.konghq.com_kongcertificates.yaml, config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongdataplaneclientcertificates.yaml, config/crd/bases/configuration.konghq.com_kongkeys.yaml, config/crd/bases/configuration.konghq.com_kongkeysets.yaml, config/crd/bases/configuration.konghq.com_kongpluginbindings.yaml, config/crd/bases/configuration.konghq.com_kongroutes.yaml, config/crd/bases/configuration.konghq.com_kongservices.yaml, config/crd/bases/configuration.konghq.com_kongupstreams.yaml, config/crd/bases/configuration.konghq.com_kongvaults.yaml, docs/api-reference.md, test/crdsvalidation/kongconsumer/testcases/controlplaneref.go, test/crdsvalidation/kongconsumergroup/testcases/controlplaneref.go, test/crdsvalidation/kongroute/testcases/controlplaneref.go, test/crdsvalidation/kongservice/testcases/controlplaneref.go
This PR adds `kic` ControlPlaneRef type and adds some more CEL validation to the `ControlPlaneRef` struct.
Fixes #
=> feat: add `kic` ControlPlaneRef type

api/configuration/v1/kongconsumer_types.go, api/configuration/v1beta1/kongconsumergroup_types.go, config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, test/crdsvalidation/kongconsumer/testcases/cpref-update-not-allowed-for-status.go, test/crdsvalidation/kongconsumergroup/testcases/cpref-update-not-allowed-for-status.go
Allow updating `KongConsumer` and `KongConsumerGroup` when `Programmed=True` and `spec.ControlPlaneRef` is empty because `spec.ControlPlaneRef` is empty when we use them in KIC.
Fixes #118
Note: Since `spec` of `KongConsumer` and `KongConsumerGroup`  are also optional, we need to add `!has(self.spec)`. This cannot be tested in our tests but it would fail when we run `kubectl apply` on them without `spec`.
=> fix: allow updating when programmed=true and cpRef is empty for KongConsumer and KongConsumerGroup

api/konnect/v1alpha1/konnect_apiauthconfiguration_types.go, config/crd/bases/konnect.konghq.com_konnectapiauthconfigurations.yaml, docs/konnect-api-reference.md, test/crdsvalidation/konnectapiauthconfiguration/konnectapiauthconfiguration_test.go, test/crdsvalidation/konnectapiauthconfiguration/testcases/common.go, test/crdsvalidation/konnectapiauthconfiguration/testcases/spec.go
Covers KonnectAPIAuthConfiguration CEL rules in tests. Allow `spec.serverURL` to be set to a full absolute URL with HTTPs scheme or just a hostname. 
Fixes https://github.com/Kong/kubernetes-configuration/issues/63.
=> chore: cover KonnectAPIAuthConfiguration CEL rules in tests

api/configuration/v1beta1/kongconsumergroup_types.go
Annotates `KongConsumerGroup` back with the KGO API reference `include` marker that was mistakenly removed in https://github.com/Kong/kubernetes-configuration/commit/b53eed6636122b0e5c818b776606444cf3815625.
=> fix: add KongConsumerGroup back to KGO reference

api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, config/crd/bases/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, test/crdsvalidation/konnectgatewaycontrolplane_test.go
Adds CEL rules for `KonnectGatewayControlPlane` `spec.labels` and covers those with tests.
Part of https://github.com/Kong/gateway-operator/issues/771.
=> feat: validate KonnectGatewayControlPlane labels

api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, config/crd/bases/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, test/crdsvalidation/konnectgatewaycontrolplane_test.go
This PR makes `KonnectGatewayControlPlane`'s `cluster_type` immutable.
The reason for this to not be conditional on the fact whether the CP is Programmed is purely to guard users from broken state when an API request to create a CP is being made and before a successful request is being processed in the operator (and thus status condition updated), user manages to change the CP type.
=> konnect: make KonnectGatewayControlPlane's cluster_type immutable

api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, config/crd/bases/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, test/crdsvalidation/konnectgatewaycontrolplane_test.go
Previous change #135, made `KonnectGatewayControlPlanes`s broken, and KGO returning the following error when applying `KonnectGatewayControlPlane` objects without `cluster_type` specified:
```
{"level":"error","ts":"2024-10-24T17:29:11.935+0200","msg":"Reconciler error","controller":"KonnectGatewayControlPlane","controllerGroup":"konnect.konghq.com","controllerKind":"KonnectGatewayControlPlane","KonnectGatewayControlPlane":{"name":"test1","namespace":"default"},"namespace":"default","name":"test1","reconcileID":"c7513c87-a811-48e1-8070-701b5c40094f","error":"failed to patch status with APIAuthResolvedRef condition: KonnectGatewayControlPlane.konnect.konghq.com \"test1\" is invalid: <nil>: Invalid value: \"object\": no such key: cluster_type …
```
=> fix(konnect): fix cluster_type validation rule on `KonnectGatewayControlPlanes`

docs/konnect-api-reference.md, go.mod, go.sum, test/crdsvalidation/konnectgatewaycontrolplane_test.go
Bump to https://github.com/Kong/sdk-konnect-go/releases/tag/v0.1.2
This release removes HYBRID CP type: https://github.com/Kong/platform-api/pull/767
=> chore: bump sdk-konnect-go to 0.1.2

config/crd/incubator/kustomization.yaml
Adds a kustomization file so it can be used externally. It's needed in KIC to replace in-tree CRDs: https://github.com/Kong/kubernetes-ingress-controller/pull/6619
=> chore: add kustomization file for incubator CRDs

api/configuration/v1alpha1/kong_vault_types.go, config/crd/bases/configuration.konghq.com_kongvaults.yaml, test/crdsvalidation/kongvault_test.go
`KongVault`'s CEL validation prevents updates of an object without a CP ref set due to reference to a non-existing field. This PR fixes the validation rule to that into account.
```console
KongVault.configuration.konghq.com "test-2lqs2" is invalid: <nil>: Invalid value: "object": no such key: controlPlaneRef evaluating rule: spec.controlPlaneRef is immutable when an entity is already Programmed
```
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6578.
=> fix: allow updating KongVault with empty CP ref

api/configuration/v1alpha1/kong_custom_entity_types.go, api/configuration/v1alpha1/kong_license_types.go
Add `apireference:kic:include` in `KongLicense` and `KongCustomEntity` to make them appear in KIC's CRD apidoc.
Part of #149 
=> chore: add apireference:kic:include for KongLicense and KongCustomEntity

go.mod, pkg/metadata/plugins.go, pkg/metadata/plugins_test.go
This PR adds a couple of handful funcs for interacting with objects' plugins through annotations:
```
func ExtractPlugins(obj ObjectWithAnnotationsAndNamespace) []string
func ExtractPluginsNamespacedNames(obj ObjectWithAnnotationsAndNamespace) []types.NamespacedName
func ExtractPluginsWithNamespaces(obj ObjectWithAnnotationsAndNamespace) []string
```
Results from added benchmarks:
```
$go test -benchmem -bench . -run ^$ -count 1  ./pkg/metadata
goos: darwin
goarch: arm64
pkg: github.com/kong/kubernetes-configuration/pkg/metadata
cpu: Apple M1 Max
BenchmarkTestExtractPlugins/0000-10                     236752966                4.776 ns/op           0 B/op          0 allocs/op
BenchmarkTestExtractPlugins/0001-10                     21764281 …
```
=> feat: add more plugin annotation funcs

api/incubator/v1alpha1/kongservicefacade_types.go
Add  `apireference:kic:include` marker for `KongServiceFacade` to make the `crd-ref-gen` to recognize it and generate docs for it. 
Required for https://github.com/Kong/kubernetes-ingress-controller/pull/6627.
=> Add apireference:kic:include marker for KongServiceFacade

.github/workflows/release.yaml, .github/workflows/tests.yaml, CHANGELOG.md, README.md
Adds a `release.yaml` workflow. It's meant to be triggered manually to create proper GH releases.
Tested on fork: 
- workflow run: https://github.com/czeslavo/kubernetes-configuration/actions/runs/12034412037
- GH release: https://github.com/czeslavo/kubernetes-configuration/releases/tag/v1.0.0-rc.1
Closes https://github.com/Kong/kubernetes-configuration/issues/150.
=> chore: add release workflow

.github/workflows/release.yaml, CHANGELOG.md
This PR fixes 3 things:
- changes the installation commands in release template to work in all shells ( lacking `?` makes this not work with `zsh`)
- fixes links in changelog
- moves the diff link next to the release heading: this way it's harder to forget about
While at it, use `${{ github.repository }}` where possible in release template.
Fixes #
=> chore: fix changelog links and make install commands work in all shells

api/configuration/v1alpha1/kong_custom_entity_types.go, config/crd/ingress-controller/configuration.konghq.com_kongcustomentities.yaml, docs/api-reference.md, test/crdsvalidation/kongcustomentity_test.go
Add KongCustomEntity's `spec.parentRef.kind` validation. Additionally add tests for that in crd validation suite.
Fixes #179
=> feat: add KongCustomEntity's `spec.parentRef.kind` validation

CHANGELOG.md, README.md
=> chore: prepare v1.0.0-rc.1

renovate.json
kustomize uses prefixed tags, e.g. https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.5.0 which does not work with default kustomize config.
This PR fixes it by adding a custom `extractVersion`.
Tested via:
```
docker run --rm -it -v $PWD/renovate.json:/usr/src/app/renovate.json -v /tmp:/tmp -v $(pwd):/tmp/workdir -w /tmp/workdir -e LOG_LEVEL=debug -e GITHUB_COM_TOKEN=${GITHUB_TOKEN} renovate/renovate --platform local --base-dir /tmp/
...
{
"depName": "kubernetes-sigs/kustomize",
"currentValue": "5.3.0",
"datasource": "github-releases",
"replaceString": "# renovate: datasource=github-releases depName=kubernetes-sigs/kustomize\nkustomize: \"5.3.0\"",
"updates": [
{
"bucket": "minor",
"newVersion": "5.5.0",
"newValue": "5.5.0", …
```
=> chore(ci): fix extractVersion for kustomize

api/configuration/v1alpha1/key_set_ref.go, api/configuration/v1alpha1/konnect_controlplaneref_types.go, config/crd/gateway-operator/configuration.konghq.com_kongcacertificates.yaml, config/crd/gateway-operator/configuration.konghq.com_kongcertificates.yaml, config/crd/gateway-operator/configuration.konghq.com_kongconsumergroups.yaml, config/crd/gateway-operator/configuration.konghq.com_kongconsumers.yaml, config/crd/gateway-operator/configuration.konghq.com_kongdataplaneclientcertificates.yaml, config/crd/gateway-operator/configuration.konghq.com_kongkeys.yaml, config/crd/gateway-operator/configuration.konghq.com_kongkeysets.yaml, config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml, config/crd/gateway-operator/configuration.konghq.com_kongroutes.yaml, config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml, config/crd/gateway-operator/configuration.konghq.com_kongupstreams.yaml, config/crd/gateway-operator/configuration.konghq.com_kongvaults.yaml, config/crd/ingress-controller/configuration.konghq.com_kongconsumergroups.yaml, config/crd/ingress-controller/configuration.konghq.com_kongconsumers.yaml, config/crd/ingress-controller/configuration.konghq.com_kongvaults.yaml, docs/api-reference.md, test/crdsvalidation/kongkey_test.go, test/crdsvalidation/suite_crd_ref_change_test.go
`konnectID` references were not implemented as part of KGO 1.4. This PR enforces this at the API level.
Fixes #
=> fix: disallow konnectID references

.github/workflows/release.yaml, .github/workflows/release_on_version_change.yaml
Should fix https://github.com/Kong/kubernetes-configuration/actions/runs/12674261856. 
Permissions reference: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release--fine-grained-access-tokens
=> chore: add contents:write permission to release workflow

.gitattributes, CHANGELOG.md, test/crdsvalidation/testcase.go
Expose `scheme` param to allow call sites to provide a scheme which is not `github.com/kong/kubernetes-configuration/pkg/clientset/scheme.Scheme`.
Also update the missing Changelog entry and update .gitattributes with generated CRD yaml  paths.
Fixes #
=> feat: add scheme param to crd validation testcase types

CHANGELOG.md, api/configuration/v1alpha1/kongpluginbinding_types.go, api/configuration/v1alpha1/zz_generated.deepcopy.go, config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml, docs/api-reference.md, test/crdsvalidation/kongpluginbindings_test.go
Adds a `scope` field to the `KongPluginBindingSpec` with a default value of `OnlyTargets` that preserves the previous default behavior (applying a plugin to targets). Also adds `GlobalInControlPlane` enum value that allows configuring a plugin to be applied globally to a control plane.
Closes #7. Part of https://github.com/Kong/gateway-operator/issues/440.
=> feat: add KongPluginBinding scope

.github/workflows/release.yaml, .github/workflows/tests.yaml
When this branch gets merged, we'll add branch protection rules for `release/*` branches.
Fixes #
=> chore(ci): add tests running on CI for release branches, limit permissions of GITHUB_TOKEN

api/configuration/v1alpha1/kongpluginbinding_types.go, config/crd/gateway-operator/configuration.konghq.com_kongpluginbindings.yaml, go.mod, test/crdsvalidation/kongcacertificate_test.go, test/crdsvalidation/kongcertificate_test.go, test/crdsvalidation/kongconsumer_test.go, test/crdsvalidation/kongconsumergroup_test.go, test/crdsvalidation/kongdataplaneclientcertificate_test.go, test/crdsvalidation/kongkey_test.go, test/crdsvalidation/kongkeyset_test.go, test/crdsvalidation/kongpluginbindings_test.go, test/crdsvalidation/kongroute_test.go, test/crdsvalidation/kongservice_test.go, test/crdsvalidation/kongupstream_test.go, test/crdsvalidation/kongvault_test.go, test/crdsvalidation/suite_crd_ref_change_test.go, test/crdsvalidation/testcase.go
CRD validation suite was missing an `assert.NoError(t, err)` when `tc.ExpectedErrorMessage == nil`. This PR adds that.
On top of that some tests needed to be adjusted and KongPluginBinding ContorlPlaneRef validation rule: this field is a non pointer, marked as required, yet for some reason it doesn't fail validation when unset. The newly added validation rule on that field enforces that it is set.
Fixes #
=> tests: fix missing tests assertions in CRD validation suite

CHANGELOG.md, config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanes.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_gatewayconfigurations.yaml, scripts/crds-generator/main.go
Add missing `GenerateEmbeddedObjectMeta` flag when generating CRDs. This is necessary to align with existing KGO CRDs (this option up until now has been set in https://github.com/Kong/gateway-operator/blob/26c8db7b0f86bfd6edbdd36033efbda1de5ae90e/Makefile#L293).
Fixes #
=> fix: generate CRDs' embedded object meta

Makefile, api/konnect/v1alpha1/konnect_extension_types.go, config/samples/konnect_dataplane_with_konnectextension.yaml
Add a sample for DataPlane with Konnect extension (as a follow up to #315).
This will help catch errors in API vs the expected manifests to be used early.
Fixes #
=> chore: add a sample manifest for DataPlane with Konnect extension

CHANGELOG.md, api/common/consts/consts.go, api/gateway-operator/controlplane/conditions.go, api/gateway-operator/dataplane/conditions.go, api/gateway-operator/gateway/conditions.go, api/konnect/conditions.go
This pull request introduces new condition types and reasons across multiple components in the `api` package. The changes include defining new literals for condition types and reasons, and applying these in various sub-packages to standardize status reporting.
Key changes include:
* [`api/common/consts/consts.go`](diffhunk://#diff-f65991d0446b9b25a0ec8b204591d4f2e02f534ad116fea8c5eeddc6c3aeadffR1-R7): Added `ConditionType` and `ConditionReason` types to define condition literals.
* [`api/gateway-operator/controlplane/conditions.go`](diffhunk://#diff-4ede1ca2bf1be900d3660968d735c6e02e39d0e872cc9a09633d8aa6279e0296R1-R35): Introduced `ConditionTypeProvisioned` and various `ConditionReason` literals to describe the status of the ControlPlane.
* …
=> chore: migrate KGO conditions to this repo

api/gateway-operator/v1beta1/controlplane_types.go, api/gateway-operator/v1beta1/dataplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanes.yaml, test/crdsvalidation/gateway-operator.konghq.com/controlplane_test.go, test/crdsvalidation/gateway-operator.konghq.com/dataplane_test.go
With https://github.com/Kong/kubernetes-configuration/pull/331 we loosened DP and CP validation by allowing empty `DeploymentSpec`. This is wrong as DP and CP are not allowed to have empty `DeploymentSpec`. This PR fixes that regression.
Fixes #
=> revert: DP and CP empty deploymentSpec not allowed

CHANGELOG.md, api/gateway-operator/dataplane/conditions.go
This pull request introduces new constants related to the BlueGreen deployment strategy for the DataPlane component. These changes help in tracking the status and reasons for various stages of the DataPlane rollout process.
part of https://github.com/Kong/kubernetes-configuration/issues/303
=> chore: migrate KGO bluegreen conditions

api/gateway-operator/v1beta1/gatewayconfiguration_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_gatewayconfigurations.yaml
For `ControlPlane` [e.kind == 'DataPlaneMetricsExtension'](https://github.com/Kong/kubernetes-configuration/blob/da21a286cd79d5c7decf1e64c8f801567fb57d0b/api/gateway-operator/v1beta1/controlplane_types.go#L92) is allowed, but for `GatewayConfiguration` it is missing which makes [TestControlPlaneExtensions_DataPlaneMetrics in KGO EE fail](https://github.com/Kong/gateway-operator-enterprise/blob/b332d3b9cd3256ba52e6be674b50df540b6b3439/test/integration/test_controlplane_extensions_dataplanemetrics.go#L179-L196). This PR fixes it
=> fix: allow `DataPlaneMetricsExtension` for `GatewayConfiguration`

api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, test/crdsvalidation/konnect.konghq.com/konnectgatewaycontrolplane_test.go
Noticed in https://github.com/Kong/gateway-operator/actions/runs/13786423423/job/38558100419?pr=1315#step:5:1378
```
konnect_entities_kongservice_test.go:165: 
Error Trace:	/home/runner/work/gateway-operator/gateway-operator/test/helpers/deploy/deploy_resources.go:203
/home/runner/work/gateway-operator/gateway-operator/test/helpers/deploy/deploy_resources.go:245
/home/runner/work/gateway-operator/gateway-operator/test/envtest/konnect_entities_kongservice_test.go:165
Error:      	Received unexpected error:
KonnectGatewayControlPlane.konnect.konghq.com "cp-a55b3655" is invalid: spec: Invalid value: "object": no such key: cloud_gateway evaluating rule: cloud_gateway cannot be set for cluster_type 'CLUSTER_TYPE_K8S_INGRESS_CONTROLLER'
Test: …
```
=> fix(konnect): fix KonnectGatewayControlPlane CEL rules checking `cloud_gateway` field

api/gateway-operator/controlplane/conditions.go
Adds `MissingReferenceGrants` condition reason
Used by https://github.com/Kong/gateway-operator/pull/1388
Fixes #
=> feat(controlplane): add MissingReferenceGrants reason

api/gateway-operator/v1beta1/dataplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanes.yaml, test/crdsvalidation/gateway-operator.konghq.com/dataplane_test.go
This PR fixes rollout in progress validation for `DataPlane` objects.
Up until now we have not checked if `status` is set which caused some flakiness in tests, e.g. 
```
test_dataplane_bluegreen.go:295: 
Error Trace:	/home/runner/go/pkg/mod/github.com/kong/gateway-operator@v1.5.1-0.20250326114827-ba5884dd83f7/test/integration/test_dataplane_bluegreen.go:502
/home/runner/go/pkg/mod/github.com/kong/gateway-operator@v1.5.1-0.20250326114827-ba5884dd83f7/test/integration/test_dataplane_bluegreen.go:295
Error:      	Received unexpected error:
DataPlane.gateway-operator.konghq.com "5dac8413-4250-497a-9bc5-a2cd9313ba7b" is invalid: <nil>: Invalid value: "object": no such key: conditions evaluating rule: DataPlane spec cannot be updated when promotion is in …
```
=> fix(dataplane): fix rollout in progress validation

CHANGELOG.md, api/configuration/v1alpha1/kongroute_types.go, config/crd/gateway-operator/configuration.konghq.com_kongroutes.yaml, test/crdsvalidation/configuration.konghq.com/kongroute_test.go
Required by PR
- https://github.com/Kong/gateway-operator/pull/1492
Adjust validation rules for `KongRoute` to allow migration from serviceless (`KonnectGatewayControlPlane` bound) to `KongService` bound and vice versa. 
Part of https://github.com/Kong/gateway-operator/issues/668
Inspired by how it looks for `Key` and `KeySet`, which supports such migration. 
Furthermore, validation for a rule with the message `spec.controlPlaneRef is immutable when an entity is already Programmed` is changed, because otherwise, in a controller logs
```log
2025-04-15T15:05:52+02:00	ERROR	Reconciler error	{"controller": "KongRoute", "controllerGroup": "configuration.konghq.com", "controllerKind": …
```
=> chore: adjust validation for `KongRoute` to allow migration from serviceless to service bound

CHANGELOG.md, api/gateway-operator/v1beta1/dataplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanes.yaml
This pull request introduces support for the Kubernetes scale subresource in the `DataPlane` custom resource definition (CRD) for the Gateway Operator. The changes enhance the CRD by enabling horizontal scaling capabilities and providing necessary paths for replicas and selectors.
* **Added scale subresource annotation in `dataplane_types.go`:**
- Included the `+kubebuilder:subresource:scale` annotation to define paths for `spec.replicas`, `status.replicas`, and `status.selector`.
part of https://github.com/Kong/gateway-operator/issues/1498
=> feat: add scale subresource for DataPlane

api/gateway-operator/controlplane/conditions.go
Extracting condition reasons and type to kubernetes-configuration from https://github.com/Kong/gateway-operator/pull/1410.
Fixes #
=> feat(controlplane): add WatchNamespaceGrantValid condition type with reasons

CHANGELOG.md, api/gateway-operator/v1beta1/dataplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanes.yaml, test/crdsvalidation/common/testcase.go, test/crdsvalidation/gateway-operator.konghq.com/dataplane_test.go
To prevent errors like these ones (KGO spotted in integration tests):
https://github.com/Kong/gateway-operator/actions/runs/15166190692/job/42644559491#step:5:3100
```
dataplane_bluegreen_test.go:295: 
Error Trace:	/home/runner/work/gateway-operator/gateway-operator/test/integration/dataplane_bluegreen_test.go:502
/home/runner/work/gateway-operator/gateway-operator/test/integration/dataplane_bluegreen_test.go:295
Error:      	Received unexpected error:
DataPlane.gateway-operator.konghq.com "2093e52b-8987-40f1-bf91-305ad189d12b" is invalid: <nil>: Invalid value: "object": no such key: conditions evaluating rule: DataPlane spec cannot be updated when promotion is in progress
Test:       	TestDataPlaneBlueGreenHorizontalScaling
```
fix `DataPlane`'s …
=> fix(dataplane): fix DataPlane CEL for spec updates during blue green rollout

api/gateway-operator/v1beta1/controlplane_types.go, api/gateway-operator/v2alpha1/controlplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml
To allow usage of new `ControlPlane` version: `v2alpha1` in KGO we need to change the storage version of that CRD to be `v2alpha1`.
This is a breaking change.
Part of https://github.com/Kong/gateway-operator/issues/1607
=> chore!: change storage version of ControlPlane to v2alpha1

.custom-gcl.yml, .golangci-kube-api.yaml, Makefile, api/konnect/v1alpha1/konnect_apiauthconfiguration_types.go, api/konnect/v1alpha1/konnect_cloudgateway_dataplane_configuration_types.go, api/konnect/v1alpha1/konnect_cloudgateway_network_types.go, api/konnect/v1alpha1/konnect_cloudgateway_transitgateway_types.go, api/konnect/v1alpha1/konnect_entity_status.go, api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, api/konnect/v1alpha2/konnect_extension_types.go, renovate.json
Can't add it for konnect/v1alpha2 because of the `map[string]DataPlaneLabelValue` usage. Related issue: https://github.com/kubernetes-sigs/kube-api-linter/issues/101
Fixes #
=> ci: add kube-api-linter for konnect/v1alpha1

CHANGELOG.md, api/gateway-operator/v1alpha1/dataplane_metrics_extension_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanemetricsextensions.yaml, docs/all-api-reference.md, docs/gateway-operator-api-reference.md
For KO everything is OSS, so marking CRD as EE only is redundant
Leftover from
- https://github.com/Kong/gateway-operator/issues/1493
=> chore: do not mark `DataPlaneMetricsExtension` as EE only

CHANGELOG.md, api/configuration/v1beta1/kongupstreampolicy_types.go, config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml, config/samples/kongupstreampolicy_hashon_cookie.yaml, config/samples/kongupstreampolicy_hashon_header_hashonfallback_cookie.yaml, docs/all-api-reference.md, docs/configuration-api-reference.md, test/crdsvalidation/configuration.konghq.com/kongupstreampolicy_test.go
Make sure that users can use `hash_on_fallback` with `cookie` when `hash_on` is set to something else.
This is a backported version of #499
Fixes #
Related PR in KIC https://github.com/Kong/kubernetes-ingress-controller/pull/7583
=> fix: fix KongUpstreamPolicy CRD CEL validation rules on hash_on

api/gateway-operator/v1beta1/controlplane_types.go, api/gateway-operator/v1beta1/gatewayconfiguration_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_gatewayconfigurations.yaml
When applying manifests with multiple objects users can receive the following deprecation notices:
```
Warning: This API version has been deprecated in favor of v2alpha1 and it will be removed in the future.
Warning: This API has been deprecated in favor of v2alpha1 API version and it will be removed in future.
```
which currently come from `ControlPlane` and `GatewayConfiguration` `v1beta1`.
This is ambiguous and makes it hard to track down which type is indeed deprecated.
This PR fixes it by making the deprecation notices explicitly call out the kind and API version.
Fixes #
=> chore: explicitly state kind and version in deprecation notice

CHANGELOG.md, api/gateway-operator/controlplane/conditions.go
- The PodsReady reason has been changed to Provisioned.
- The PodsNotReady reason has been changed to ProvisioningInProgress.
Related to https://github.com/Kong/kong-operator/issues/1948
=> chore: CP provisioning reasons renamed

api/gateway-operator/v2beta1/controlplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml
Operator doesn't use the `Scheduled` condition anymore, it only uses `Provisioned` so change the default to contain the latter only.
Fixes #
=> feat(controlplane): change the default status condition for ControlPlane to Provisioned

CHANGELOG.md, api/gateway-operator/v1beta1/controlplane_conversion.go, api/gateway-operator/v1beta1/controlplane_types.go, test/conversion/gateway-operator.konghq.com/v1beta1/controlplane_test.go
Implements conversion for `ControlPlane` from `v1beta1` to `v2beta1`, which should cover most cases and features that may be configured using the old method and maps to the new one. Status does not need explicit conversion. Ignoring it just works. It will be properly set in the expected format and work (readiness is detected) when the change from PR https://github.com/Kong/kong-operator/pull/2057 will be merged (small workaround and actual usage of code from this PR)
Part of https://github.com/Kong/kong-operator/issues/1368
Of course, after the merge bump of this library has to happen in the KO repo.
=> feat: conversion for `ControlPlane` from `v1beta1` to `v2beta1`

api/gateway-operator/v1beta1/controlplane_conversion.go, test/conversion/gateway-operator.konghq.com/v1beta1/controlplane_test.go
Without this fix, an attempt to apply, e.g. [controlplane-dataplane-watchnamespaces.yaml](https://github.com/Kong/kong-operator/blob/main/config/samples/controlplane-dataplane-watchnamespaces.yaml) ends with a failure like that
```json
{"level":"error","ts":"2025-08-28T13:41:09Z","msg":"Reconciler error","controller":"controlplane","controllerGroup":"gateway-operator.konghq.com","controllerKind":"ControlPlane","ControlPlane":{"name":"controlplane-example","namespace":"default"},"namespace":"default","name":"controlplane-example","reconcileID":"f09b58aa-82b4-46b8-8169-3b82009292f2","error":"failed to patch ControlPlane status with DataPlane name dataplane-cp-watchnamespace: ControlPlane.gateway-operator.konghq.com \"controlplane-example\" is invalid: …
```
=> fix: set default IngressClass for `ControlPlane` conversion
