.github/ISSUE_TEMPLATE/---bug.md, .github/ISSUE_TEMPLATE/--enhancement---feature---task.md
Addition of the issue templates.
Fixes #
=> chore: add issue templates

.github/workflows/tests.yaml, .tools_versions.yaml, Makefile, api/configuration/v1alpha1/kongservice_types.go, api/konnect/v1alpha1/konnect_entity_status.go, go.mod, test/kongservice_test.go
This PR will allow to perform interface assertions and set/get Konnect ControlPlane ID uniformly across types that reference a CP.
Fixes #
=> refactor: add ControlPlane ref funcs

pkg/metadata/consts.go, pkg/metadata/tags.go, pkg/metadata/tags_test.go
Add `ExtractTags` and related exported consts.
=> feat: add ExtractTags

api/configuration/v1/kongconsumer_types.go, api/configuration/v1alpha1/kongpluginbinding_types.go, api/configuration/v1alpha1/kongroute_types.go, api/configuration/v1alpha1/kongservice_types.go, api/configuration/v1beta1/kongconsumergroup_types.go, test/unit/kongconsumergroup_test.go, test/unit/kongpluginbinding_test copy.go
=> chore: added get/set functions to `PluginBinding`

api/configuration/v1alpha1/kongcredential_apikey_types.go, config/crd/bases/configuration.konghq.com_kongcredentialapikeys.yaml, config/samples/konnect_kongconsumer_apikey.yaml, docs/api-reference.md
Fix broken struct tag in `KongCredentialAPIKey`.
=> fix: fix json struct tag in KongCredentialAPIKey

README.md
=> chore: update README about release process

api/configuration/v1alpha1/kongservice_types.go, config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml
Fix a typo in `KongService`'s printcolumn
=> chore: fix KongService's protocol printcolumn

CHANGELOG.md
:shipit: 
Required for 
- https://github.com/Kong/kubernetes-ingress-controller/issues/6635
=> chore: prepare release v1.0.0

.github/workflows/release.yaml, .github/workflows/tests.yaml, .tools_versions.yaml, Makefile
Add [`actionlint`](https://github.com/rhysd/actionlint) in CI with [`shellcheck`](https://github.com/koalaman/shellcheck) integration.
Fixes #
=> ci: add actionlint in CI

.github/workflows/release.yaml, .github/workflows/tests.yaml
Fix the release workflow by using the boolean `true` in comparison.
Fixes #
=> chore(ci): fix release on version change workflow

.github/workflows/release.yaml, .github/workflows/release_on_version_change.yaml, .github/workflows/tests.yaml
Pin all 3rd party actions by hashes.
Fixes #
=> Chore(ci): pin 3rd party actions by hashes

.github/workflows/codeql.yaml
=> chore(ci): add codeql code scanning

.github/workflows/release_on_version_change.yaml, .github/workflows/tests.yaml
=> chore(ci): pin actions and ensure they are pinned

test/crdsvalidation/testcase.go
This PR solves an issue where the assert is being done in eventual manner and hence the object that's being passed to `Create()` will be overwritten by the first failed `Create()` causing:
```
resourceVersion should not be set on objects to be created
```
Fixes #
=> tests: fix CRD validation test suite

api/configuration/v1alpha1/kongservice_types.go, config/crd/gateway-operator/configuration.konghq.com_kongservices.yaml, docs/api-reference.md
Fix the comments on `KongServiceSpec` from `Kong Route` to `Kong Service`. 
Fixes #
=> chore: Fix comments on KongServiceSpec

api/konnect/v1alpha1/konnect_conditions.go
To be used by https://github.com/Kong/gateway-operator/pull/1099
Fixes #
=> chore: add KonnectEntityProgrammedReasonExistsConditionWithStatusFalse condition reason

api/konnect/v1alpha1/konnect_conditions.go
=> chore: rename ExistsConditionWithStatusFalse -> ConditionWithStatusFalseExists

CHANGELOG.md, api/konnect/v1alpha1/konnect_conditions.go, api/konnect/v1alpha1/konnect_extension_types.go, config/crd/gateway-operator/konnect.konghq.com_konnectextensions.yaml
Fixes https://github.com/Kong/kubernetes-configuration/issues/292
=> feat: KonnectExtension conditions

api/konnect/v1alpha1/konnect_conditions.go
=> feat: add invalid secret condition for `KonnectExtension`s

api/gateway-operator/v1beta1/controlplane_types.go, api/gateway-operator/v1beta1/dataplane_types.go
=> feat: added GetExtensions methods to CP and DP

api/configuration/v1/zz_generated_funcs.go, api/configuration/v1alpha1/zz_generated_funcs.go, api/configuration/v1beta1/zz_generated_funcs.go, api/konnect/v1alpha1/zz_generated_funcs.go, api/konnect/v1alpha1/zz_generated_funcs_standalone.go, api/konnect/v1alpha1/zz_generated_list_funcs.go, scripts/apitypes-funcs/main.go, scripts/apitypes-funcs/supportedtypes.go, scripts/apitypes-funcs/templates.go
=> feat: add GetControlPlaneRef and SetControlPlaneRef to KonnectExtension

api/konnect/v1alpha1/konnect_gateway_controlplane_types.go, config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml, test/crdsvalidation/konnect.konghq.com/konnectgatewaycontrolplane_test.go
=> feat: disallow cloud_gateway for KIC KonnectGatewayControlPlane

api/konnect/v1alpha1/konnect_extension_types.go, config/crd/gateway-operator/konnect.konghq.com_konnectextensions.yaml
=> feat: add ready column to KonnectExtension

test/crdsvalidation/common/testcase.go
Before making an update in K8s, the best pattern is first to get and then update. In case of error, just perform a retry, because it may be a conflict (some fields were updated).
Discovered during work on 
- https://github.com/Kong/kubernetes-configuration/pull/386
See the https://github.com/Kong/kubernetes-configuration/pull/386#discussion_r2046886684
=> chore: make update in assertion an actual update

api/common/v1alpha1/doc.go, api/gateway-operator/v1alpha1/groupversion_info.go, api/gateway-operator/v1beta1/groupversion_info.go, docs/all-api-reference.md, docs/gateway-operator-api-reference.md
=> chore: remove duplicated doc comments

CHANGELOG.md, api/configuration/v1/kongingress_types.go, api/configuration/v1beta1/tcpingress_types.go, api/configuration/v1beta1/udpingress_types.go, config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml, config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml, config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml, docs/all-api-reference.md, docs/configuration-api-reference.md
part of https://github.com/Kong/kubernetes-ingress-controller/issues/7496
=> deprecate: KongIngress, TCPIngress, UDPIngress

api/configuration/v1beta1/kongupstreampolicy_types.go, config/crd/ingress-controller/configuration.konghq.com_kongupstreampolicies.yaml, test/crdsvalidation/configuration.konghq.com/kongupstreampolicy_test.go
Fixes #
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes~
=> add CEL validation for stickySessions and algorithm field

CHANGELOG.md
=> chore: fix changelog for 1.4.2

Makefile, api/common/v1alpha1/controlplaneref_types.go, api/common/v1alpha1/extensionref_types.go, api/common/v1alpha1/objectref_types.go, config/crd/gateway-operator/konnect.konghq.com_konnectextensions.yaml
=> chore: add kube linter for common v1alpha1 types

CHANGELOG.md, api/configuration/v1/kongingress_types.go, api/configuration/v1beta1/tcpingress_types.go, api/configuration/v1beta1/udpingress_types.go, config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml, config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml, config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml, docs/all-api-reference.md, docs/configuration-api-reference.md
This pull request updates the deprecation notices for `KongIngress`, `TCPIngress`, and `UDPIngress` resources across multiple files to include links to their respective migration guides. 
Fixes #
Although the current document still needs improvement, our subsequent modifications will also be in that location, so it is safe to use its link.
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes~
=> docs: clean todos for migration

CHANGELOG.md, api/configuration/v1/kongingress_types.go, api/configuration/v1beta1/tcpingress_types.go, api/configuration/v1beta1/udpingress_types.go, config/crd/ingress-controller/configuration.konghq.com_kongingresses.yaml, config/crd/ingress-controller/configuration.konghq.com_tcpingresses.yaml, config/crd/ingress-controller/configuration.konghq.com_udpingresses.yaml, docs/all-api-reference.md, docs/configuration-api-reference.md
* remove TODOs and add migration documentation links
* make generate
---------
cherry-pick #489 
Fixes #
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes~
=> docs: clean todos for migration (#489)

api/gateway-operator/v2alpha1/gvrs.go
There is `ControlPlaneGVR()` add a similar `GatewayConfigurationGVR()`, it's good to have such an introspection available.
=> feat: add function `GatewayConfigurationGVR()`

api/gateway-operator/v1alpha1/aigateway_types.go, api/gateway-operator/v1beta1/dataplane_types.go, api/gateway-operator/v2beta1/controlplane_types.go, api/gateway-operator/v2beta1/gatewayconfiguration_types.go, api/konnect/v1alpha1/konnect_cloudgateway_dataplane_configuration_types.go, api/konnect/v1alpha2/konnect_extension_types.go, api/konnect/v1alpha2/konnect_gateway_controlplane_types.go, config/crd/gateway-operator/gateway-operator.konghq.com_aigateways.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_controlplanes.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_dataplanes.yaml, config/crd/gateway-operator/gateway-operator.konghq.com_gatewayconfigurations.yaml, config/crd/gateway-operator/konnect.konghq.com_konnectcloudgatewaydataplanegroupconfigurations.yaml, config/crd/gateway-operator/konnect.konghq.com_konnectextensions.yaml, config/crd/gateway-operator/konnect.konghq.com_konnectgatewaycontrolplanes.yaml
Add `Age` printcolumn to 
- AIGateway
- DataPlane
- ControlPlane
- GatewayConfiguration
- KonnectCloudGatewayDataPlaneGroupConfiguration
- KonnectGatewayControlPlane
Fixes #
=> feat: add age printcolumn to types

api/gateway-operator/v1beta1/controlplane_conversion.go, test/conversion/gateway-operator.konghq.com/v1beta1/controlplane_test.go
=> fix: fix spec.dataplane and IngressClass setting during ControlPlane conversion
